### ISSUE TITLE
Youtube video dataset file 

### ISSUE THREAD

**Issue by kyungjin-lee** [pedro-morgado/spatialaudiogen#1]
Hi, I'd like to ask about the dataset with 360 videos from youtube.
Could you tell me how you differentiated between EAC and ER videos?
I'd like to find more ER videos on Youtube.
It would be very helpful if you could provide how the scraping/video_formats.txt file was created.
Thank you very much!

**Comment by pedro-morgado** [comment]
I couldn't find the information about the video projection (EAC or ER) in the metadata (probably did not look hard enough). But, since I only had a couple thousand to look through, I did it manually from thumbnails. As for the dataset, I used the search capabilities of youtube-dl.
